Fix line draw bug
Error: if searching for a new neighbourhood, if you don't clear the
map before searching again, the line connects to the previous search area

This fix causes the map to be cleared on 'Go' click